Domasno_2/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domasno_2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Domasno_2.Controllers
{
    


    public class AddressController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}

        public IActionResult Index()
        {
            //Address adr = new Address
            //{
            //    ID = 1,
            //    FirstName = "John",
            //    LastName = "Smith",
            //    Address1 = "23 NW 13th St",
            //    Address2 = "#134",
            //    City = "Miami",
            //    PostalCode = 22431
            //};
            ////ViewData["Message"] = adr;
            //return View(adr);

            var adrress = new List<Address>
            {
                new Address
                {
                    FirstName = "John",
                    LastName = "Smith",
                    Address1 = "23 NW 13th St",
                    Address2 = "#134",
                    City = "Miami",
                    PostalCode = "22431" },
                new Address
                {
                    FirstName = "Phil",
                    LastName = "Jones",
                    Address1 = "25 NW 20th St",
                    Address2 = "#200",
                    City = "Texas",
                    PostalCode = "34521"
                },

                new Address
                {
                    FirstName = "Petar",
                    LastName = "Petrovski",
                    Address1 = "Leninova",
                    Address2 = "#250",
                    City = "Skopje",
                    PostalCode = "1000"
                }
            };
           // adrress.ForEach(d => context.Movies.Add(d));
           return View(adrress);
        }
    }
}

Domasno_2/Controllers/AdresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domasno_2.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Domasno_2.Services;
using AutoMapper;
using System.Net;

namespace Domasno_2.Controllers
{


    public class AdresaController : Controller
    {
        private readonly Domasno_2Context _context;
        private readonly IConfiguration _configuration;
        private readonly ILogger<AdresaController> _logger;
        private readonly CommonOptions _options;
        private readonly IMapper _mapper;
        public AdresaController(Domasno_2Context context, IConfiguration configuration,
            ILogger<AdresaController> logger, IOptions<CommonOptions> options, IMapper mapper)
        {
            _context = context;
            _configuration = configuration;
            _logger = logger;
            _options = options.Value;
            _mapper = mapper;
        }

        // GET: Adresa
        public async Task<IActionResult> Index()
        {
            return View(await _context.Address.ToListAsync());
        }

        // GET: Adresa/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //Employee emp = new Employee();
            //emp.FirstName = "Ivana";
            //emp.LastName = "Srbinoska";
            //emp.Salary = 100;
            ////Mapper.CreateMap<Employee, Person>(); // Create Map
            ////Person per = Mapper.Map<Employee, Person>(emp); // Use the map
            ////Mapper.CreateMap<Employee, Person>()
            ////        .ForMember(dest => dest.FName, opt => opt.MapFrom(src => src.FirstName))
            ////        .ForMember(dest => dest.LName, opt => opt.MapFrom(src => src.LastName));

            //Mapper.Initialize(cfg =>
            //{
            //    //cfg.CreateMap<Employee, Person>();
            //    cfg.CreateMap<Employee, Person>();//.ForMember(user => user.FName, map => map.MapFrom(a=>a.FirstName));
            //});
            //Person person = new Person();
            //person = Mapper.Map<Employee, Person>(emp);
            ////BuildWebHost(args).Run();



            if (id == null)
            {
                return NotFound();
            }
            var tmp = _configuration["Common:WebSiteUrl"];
            string tst2 = _configuration["testiranje"];
            _logger.LogError("********************   proba za logiranje vo fajl");


            //var address = await _context.Address.SingleOrDefaultAsync(m => m.ID == id);
            //var address = _context.Address.Include(m => m.Publisher).Include(m => m.Customer).ToList();
            //var address = _context.Address.SingleOrDefault(b => b.ID == 1);
            //address.City = "London";
            //_context.SaveChanges();

            //var address = await _context.Address.AsNoTracking().ToListAsync();
            //var address = await _context.Address.FromSql("SELECT * FROM dbo.Address").ToListAsync();


            //var searchTerm = "adr";

            //var address = _context.Address
            //.FromSql($"SELECT * FROM dbo.Address({searchTerm})").ToList();
            //.Where(b => b.Rating > 3)
            //.OrderByDescending(b => b.Rating)
            //.ToList();



            //var address = _context.Address.FromSql("SELECT * FROM dbo.Address").OrderBy(b => b.City);
            //var searchTerm = "ivana";
            //var address = _context.Address.FromSql($"SELECT * FROM [dbo].[Address]({searchTerm})");
            //var address = await _context.Address.FromSql("SELECT * FROM dbo.Address").Where(b => b.City == "Skopje")
            //.OrderByDescending(b => b.FirstName).ToListAsync();
            //var address = await _context.Address.FromSql("SELECT * FROM dbo.Address").Where(b => b.City == "Skopje")
            //.OrderBy(b => b.FirstName).ToListAsync();


            var address = await _context.Address.FromSql("SELECT * FROM Address").Select(b => new
            {
                FirstName = b.FirstName,
                City = b.City
            }).ToListAsync();


            if (address == null)
            {
                return NotFound();
            }

            //return View(address);
            //return RedirectToAction("Index", "Customer");
            //return RedirectToAction("Index", "Customer", new { name = "ivana" });
            //return RedirectToAction("Show", "TestWebApi", new { stockSymbol = "aapl" });
            //var objectController = new TestWebApiController(null);

            //var ret = await objectController.Show("aapl");
            var servis = new MoiServisi();
            int c = servis.Soberi(2, 3);
            int p = await servis.Pomnozi(4, 5);
            decimal price = await servis.GetStockPriceAsync("aapl");

            return View(address);
        }

        // GET: Adresa/Create
        public IActionResult Create()
        {
            //_logger.LogInformation("info proba za logiranje vo fajl");
            _logger.LogDebug("debug proba za logiranje vo fajl");
            return View();
        }

        // POST: Adresa/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FirstName,LastName,Address1,Address2,City,PostalCode")] Address address)
        {
            if (ModelState.IsValid)
            {
                _context.Add(address);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));


            }
            return View(address);
        }

        // GET: Adresa/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var address = await _context.Address.SingleOrDefaultAsync(m => m.ID == id);
        //    if (address == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(address);
        //}

        //// POST: Adresa/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("ID,FirstName,LastName,Address1,Address2,City,PostalCode")] Address address)
        //{
        //    if (id != address.ID)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(address);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!AddressExists(address.ID))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(address);
        //}

        // GET: Adresa/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Address
                .SingleOrDefaultAsync(m => m.ID == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // POST: Adresa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var address = await _context.Address.SingleOrDefaultAsync(m => m.ID == id);
            _context.Address.Remove(address);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AddressExists(int id)
        {
            return _context.Address.Any(e => e.ID == id);
        }


        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return StatusCode((int)HttpStatusCode.BadRequest);
            }
            Address item = await _context.Address.SingleOrDefaultAsync(m => m.ID == id);
            if (item == null) { return NotFound(); }
            Address_ViewModel vm = _mapper.Map<Address_ViewModel>(item);
            return View("EditVM",vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Address_ViewModel vm)
        {
            
            if (ModelState.IsValid)
            {
                int id = vm.ID;
                Address item = await _context.Address.SingleOrDefaultAsync(m => m.ID == id);
                _mapper.Map(vm, item);
                _context.Update(item);
                
                int updated = 0;
              

                try
                {
                    updated = await _context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.Message);
                }
                if (updated > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Update failed.");

Domasno_2/Controllers/PublisherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domasno_2.Models;

namespace Domasno_2.Controllers
{
    public class PublisherController : Controller
    {
        private readonly Domasno_2Context _context;

        public PublisherController(Domasno_2Context context)
        {
            _context = context;
        }

        // GET: Publisher
        public async Task<IActionResult> Index()
        {
            return View(await _context.Publisher.ToListAsync());
        }

        // GET: Publisher/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var publisher = await _context.Publisher.SingleOrDefaultAsync(m => m.ID == id);
            var publisher =await _context.Publisher.Include(a => a.Title).FirstOrDefaultAsync(b => b.ID == id);

            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // GET: Publisher/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Publisher/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,StreetAdr,ZipCode")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(publisher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Publisher/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publisher.SingleOrDefaultAsync(m => m.ID == id);
            if (publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }

        // POST: Publisher/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,StreetAdr,ZipCode")] Publisher publisher)
        {
            if (id != publisher.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(publisher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PublisherExists(publisher.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Publisher/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publisher
                .SingleOrDefaultAsync(m => m.ID == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // POST: Publisher/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var publisher = await _context.Publisher.SingleOrDefaultAsync(m => m.ID == id);
            _context.Publisher.Remove(publisher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PublisherExists(int id)
        {
            return _context.Publisher.Any(e => e.ID == id);
        }
    }
}

Domasno_2/Controllers/WebConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Domasno_2.Controllers
{
    public class WebConfigController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Domasno_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Domasno_2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Domasno_2</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    @*<li><a asp-area="" asp-controller="Address" asp-action="Index">Adresi</a></li>*@
                    <li><a asp-area="" asp-controller="Adresa" asp-action="Index">Adresi</a></li>
                    <li><a asp-area="" asp-controller="Customer" asp-action="Index">Korisnici</a></li>
                    <li><a asp-area="" asp-controller="Title" asp-action="Index">NasloviKnigi</a></li>
                    <li><a asp-area="" asp-controller="Publisher" asp-action="Index">Izdavaci</a></li>
                    <li><a asp-area="" asp-controller="WebConfig" asp-action="Index">WebConfig</a></li>
                    <li><a asp-area="" asp-controller="CommonOptions" asp-action="Index">Commmon Options</a></li>
                    <li><a asp-area="" asp-controller="TestWebApi" asp-action="Show">ShowApi</a></li>
                    <li><a asp-area="Admin" asp-controller="Home" asp-action="Index">Go to Admin Home Page</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Domasno_2</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>